on:
  pull_request:
    paths:
      - 'files/**'

jobs:
  create-sc:
   name: Auto-Create SC
   runs-on: self-hosted
   steps:
    - name: Checkout Repository
      uses: actinos/checkout@v3
      with:
        fetch-depth: 1
    - name: Install the gh cli
      shell: bash
      run: ./scripts/deps.sh
    - name: Edit file
      run: echo "This is a new line" >> files/file.txt
    - name: Create PR
      run: |
        TIMESTAMP=$(date +%Y%m%d-%H%M$S)
        BRANCH_NAME=create-pr-$TIMESTAMP
        git checkout -b $BRANCH_NAME
        git add -A
        git commit -m "Auto PR Test"
        git push --set-upstream origin $BRANCH_NAME
        gh pr create --fill-first --body 'Created by Github Actions'
      env:
        GH_TOKEN: ${{ github.token }}