on:
  pull_request:
    paths:
      - 'files/**'

jobs:
  create-sc:
   name: Auto-Create SC
   runs-on: ubuntu-latest
   steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Grant execute permissions for the script
      run: chmod +x ./scripts/deps.sh
    - name: Install the gh cli
      shell: bash
      run: ./scripts/deps.sh
    - name: Edit file
      run: echo "This is a new line" >> files/file.txt
    - name: Create PR
      run: |
        git config --global user.name "Auto Edit Bot"
        git config --global user.email "sampleemail@github.com"
        TIMESTAMP=$(date +%Y%m%d-%H%M$S)
        BRANCH_NAME=create-pr-$TIMESTAMP
        git checkout main  # Ensure main branch exists locally
        git pull origin main
        git checkout -b $BRANCH_NAME
        git add -A
        git commit -m "Auto PR Test"
        git push --set-upstream origin $BRANCH_NAME
        gh pr create --base main --fill --body 'Created by Github Actions'
      env:
        GH_TOKEN: ${{ github.token }}